# Generated by Django 4.1 on 2022-09-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField(max_length=100)),
                ('ementa', models.CharField(max_length=100)),
                ('bibliografia', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pswAtividades.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pswAtividades.pessoa')),
                ('matricula', models.CharField(max_length=30)),
                ('situacao', models.CharField(max_length=30)),
            ],
            bases=('pswAtividades.pessoa',),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(max_length=3)),
                ('semestre', models.IntegerField(max_length=2)),
                ('dia_semana', models.IntegerField(max_length=1)),
                ('horarios', models.CharField(max_length=100)),
                ('disciplina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pswAtividades.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pswAtividades.pessoa')),
                ('titulacao_maxima', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pswAtividades.curso')),
            ],
            bases=('pswAtividades.pessoa',),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.FloatField(max_length=10)),
                ('nota2', models.FloatField(max_length=10)),
                ('nota_prova_final', models.FloatField(max_length=10)),
                ('frequencia', models.IntegerField(max_length=10)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aluno_avaliacao', to='pswAtividades.turma')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aluno_avaliacao', to='pswAtividades.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='avaliacoes',
            field=models.ManyToManyField(related_name='alunoAvaliacoes', through='pswAtividades.Avaliacao', to='pswAtividades.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pswAtividades.curso'),
        ),
    ]
