# Generated by Django 4.1 on 2022-09-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pswAtividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='frequencia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dia_semana',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turma',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
