# Generated by Django 4.1 on 2022-09-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pswAtividades', '0002_alter_avaliacao_frequencia_alter_curso_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='pre_requisito',
            field=models.ManyToManyField(to='pswAtividades.disciplina'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
