# Generated by Django 4.1 on 2022-09-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pswAtividades', '0003_disciplina_pre_requisito_alter_pessoa_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='pre_requisito',
        ),
        migrations.CreateModel(
            name='PreRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina', to='pswAtividades.disciplina')),
                ('disciplina_pre_requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_pre_requisito', to='pswAtividades.disciplina')),
            ],
        ),
    ]
