# Generated by Django 4.0.4 on 2022-09-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pswAtividades', '0004_remove_disciplina_pre_requisito_prerequisito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='nota1',
            new_name='nota_1',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='nota2',
            new_name='nota_2',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
